export const meetingMockData = [
  {
    id: 1,
    title: '전체 회의',
    description: '주간 진행 상황 공유 및 다음 일정 논의',
    date: '2026-08-12',
    time: '18:00',
    project: '노디 프로젝트',
    team: '마케팅팀',
    status: 'IN_PROGRESS',
  },
  {
    id: 2,
    title: '기획 회의',
    description: '회의 안건 및 화면 구성 논의',
    date: '2026-08-12',
    time: '20:00',
    project: '노디 프로젝트',
    team: '마케팅팀',
    status: 'SCHEDULED',
  },
  {
    id: 3,
    title: '프로젝트 회의',
    description: '프로젝트 진행 상황 공유',
    date: '2026-08-18',
    time: '15:00',
    project: '몰포 프로젝트',
    team: '마케팅팀',
    status: 'SCHEDULED',
  },
  {
    id: 4,
    title: '디자인 회의',
    description: '디자인 QA 및 수정사항 확인',
    date: '2026-08-21',
    time: '14:00',
    project: '노디 프로젝트',
    team: '디자인팀',
    status: 'SCHEDULED',
  },
];
