export const meetingMockData = [
  {
    id: 1,
    title: '전체 회의',
    description: '주간 진행 상황 공유 및 다음 일정 논의',
    date: '2026-08-12',
    startTime: '18:00',
    endTime: '19:00',
    project: '노디 프로젝트',
    team: '마케팅팀',
    participants: [
      {
        id: 1,
        name: '김민지',
        profileImageUrl: null,
      },
      {
        id: 2,
        name: '이서준',
        profileImageUrl: null,
      },
      {
        id: 3,
        name: '박지우',
        profileImageUrl: null,
      },
      {
        id: 4,
        name: '최유진',
        profileImageUrl: null,
      },
      {
        id: 5,
        name: '정현우',
        profileImageUrl: null,
      },
    ],
  },
  {
    id: 2,
    title: '기획 회의',
    description: '회의 안건 및 화면 구성 논의',
    date: '2026-08-12',
    startTime: '20:00',
    endTime: '21:00',
    project: '노디 프로젝트',
    team: '마케팅팀',
    participants: [],
  },
  {
    id: 3,
    title: '프로젝트 회의',
    description: '프로젝트 진행 상황 공유',
    date: '2026-08-18',
    startTime: '15:00',
    endTime: '16:00',
    project: '몰포 프로젝트',
    team: '마케팅팀',
    participants: [],
  },
  {
    id: 4,
    title: '디자인 회의',
    description: '디자인 QA 및 수정사항 확인',
    date: '2026-08-21',
    startTime: '14:00',
    endTime: '15:00',
    project: '노디 프로젝트',
    team: '디자인팀',
    participants: [],
  },
];
